### ISSUE TITLE
Feature request: Ability to import all staticexports from a package

### ISSUE THREAD

**Issue by rossellhayes** [wch/staticimports#18]
It would be useful to have a way to import all functions that are statically exported from a package.

For example, when developing a package, I sometimes put utility functions in `inst/staticexports` so I can reuse them in other packages. It would save time if I could include something like this in `utils.R`:

```
# @staticimports inst/staticexports
#   *
```

I'd be happy to submit a PR if this would be appreciated!

**Comment by wch** [comment]
Sounds like that could be useful. I'll definitely look at the PR, though it might not be right away -- I'll be very busy for the next few weeks.
